version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - my_network

  pgvector:
    image: phidata/pgvector:16
    container_name: pgvector
    environment:
      POSTGRES_DB: ai
      POSTGRES_USER: ai
      POSTGRES_PASSWORD: ai
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgvolume:/var/lib/postgresql/data
    ports:
      - "5532:5432"
    networks:
      - my_network

networks:
  my_network:

volumes:
  ollama:
  pgvolume:

